#!/bin/sh

# AUTHOR: koalagang (https://github.com/koalagang)
# Dependencies: doas
# You can find the doasedit repository at https://github.com/koalagang/doasedit

# handle errors
error () {
    echo "doasedit: $1" && exit 1
}

if [ -f "$1" ]; then
    no_file=1
elif [ -d "$1" ]; then
    error "$1: Is a directory"
fi

[ -z "$1" ] && error 'no file path provided'
[ -n "$2" ] && error 'expected only one argument'
[ "$(whoami)" = 'root' ] && error 'cannot be run as root'
[ -w "$1" ] && error 'editing files in a writeable directory is not permitted'

# create a temporary file which is named with the following format:
# if source file = '/etc/pacman.conf' then
# the temporary file with be '/tmp/pacmanxyz.conf' where xyz is a random string of letters and numbers
# if there is no extension then it will not contain the extension obviously
filename="$(basename -- "$1")"
temp="$(mktemp -t "${filename%.*}"XXX."${filename#*.}")"

# if the source file does not exist then create a new file and give the temporary file the relevant permissions
# if the source file does exist then simply copy its contents over to the temporary file
if [ -n "$no_file" ]; then
    cat "$1" > "$temp" && $EDITOR "$temp"
else
    $EDITOR "$temp"
fi

cmp "$1" "$temp" -s && rm "$temp" && echo "$1 unchanged" && exit 0 # if the file is unchanged then exit

# copy the contents of temporary file into the source file
# attempt three times in case the user mistypes the root password
doas dd if="$temp" of="$1" >/dev/null 2>&1 || doas dd if="$temp" of="$1" >/dev/null 2>&1 || doas dd if="$temp" of="$1" >/dev/null 2>&1

# cleanup
rm -rf "$temp"
